class Exception(object):

    def __init__(self):
        pass
